name: Build MicroROS Lib

# 触发工作流的事件
on:
  repository_dispatch:
    types: [trigger]
  push:
    branches:
      - release-github
  pull_request:
    branches:
      - release-github

jobs:
  build:
    runs-on: ubuntu-latest  # 在 GitHub 提供的虚拟机上运行
    container:
      image: microros/micro_ros_static_library_builder:humble  # 指定自定义 Docker 镜像
      options: --privileged

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Run build script
      run: |
        bash build.sh


    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: microros-artifacts
        path: artifacts
